#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

WORKLOAD_PRESET="${1:-full}"

case "$WORKLOAD_PRESET" in
  quick)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-embedded}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-1}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-1000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-50000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-200000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-2048}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-4096}"
    ;;
  full)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-embedded}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-10000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-250000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-1000000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-4096}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-4096}"
    ;;
  mixed-order)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-embedded}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-1}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-2048}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-100000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-400000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-2048}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-192}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-4}"
    export TSINK_OOO_CROSS_PARTITION_PERMILLE="${TSINK_OOO_CROSS_PARTITION_PERMILLE:-150}"
    export TSINK_OOO_CROSS_PARTITIONS="${TSINK_OOO_CROSS_PARTITIONS:-4}"
    export TSINK_PARTITION_SECONDS="${TSINK_PARTITION_SECONDS:-600}"
    ;;
  test)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-test}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-1000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-50000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-200000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-2048}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-4}"
    ;;
  edge)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-edge}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-20000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-250000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-750000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-4096}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-8}"
    ;;
  embedded)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-embedded}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-50000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-500000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-1500000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-4096}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-8}"
    ;;
  server)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-server}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-100000}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-1}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-1000000}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-3000000}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-8192}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-16}"
    ;;
  server-writers)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-server}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-1}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-0}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-0}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-1}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-8192}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-16}"
    export TSINK_NEW_SERIES_WRITERS="${TSINK_NEW_SERIES_WRITERS:-16}"
    export TSINK_NEW_SERIES_PER_WRITER="${TSINK_NEW_SERIES_PER_WRITER:-25000}"
    export TSINK_NEW_SERIES_SHARED_METRIC_NAMES="${TSINK_NEW_SERIES_SHARED_METRIC_NAMES:-1}"
    ;;
  server-queries)
    export TSINK_RESOURCE_PROFILE="${TSINK_RESOURCE_PROFILE:-server}"
    export TSINK_BPP_RUNS="${TSINK_BPP_RUNS:-3}"
    export TSINK_ACTIVE_SERIES="${TSINK_ACTIVE_SERIES:-1}"
    export TSINK_PRIME_ALL_SERIES="${TSINK_PRIME_ALL_SERIES:-0}"
    export TSINK_WARMUP_POINTS="${TSINK_WARMUP_POINTS:-0}"
    export TSINK_MEASURE_POINTS="${TSINK_MEASURE_POINTS:-1}"
    export TSINK_BATCH_SIZE="${TSINK_BATCH_SIZE:-4096}"
    export TSINK_MIN_POINTS_PER_SERIES="${TSINK_MIN_POINTS_PER_SERIES:-1}"
    export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-16}"
    export TSINK_QUERY_SATURATION_BENCH="${TSINK_QUERY_SATURATION_BENCH:-1}"
    export TSINK_QUERY_SATURATION_WORKERS="${TSINK_QUERY_SATURATION_WORKERS:-0}"
    export TSINK_QUERY_SATURATION_SERIES="${TSINK_QUERY_SATURATION_SERIES:-4096}"
    export TSINK_QUERY_SATURATION_POINTS_PER_SERIES="${TSINK_QUERY_SATURATION_POINTS_PER_SERIES:-64}"
    export TSINK_QUERY_SATURATION_SERIES_PER_QUERY="${TSINK_QUERY_SATURATION_SERIES_PER_QUERY:-128}"
    export TSINK_QUERY_SATURATION_WRITER_POINTS="${TSINK_QUERY_SATURATION_WRITER_POINTS:-100000}"
    export TSINK_QUERY_SATURATION_BATCH_SIZE="${TSINK_QUERY_SATURATION_BATCH_SIZE:-4096}"
    ;;
  *)
    echo "Unknown workload preset: $WORKLOAD_PRESET (expected: quick|full|mixed-order|test|edge|embedded|server|server-writers|server-queries)" >&2
    exit 1
    ;;
esac

case "$TSINK_RESOURCE_PROFILE" in
  test|embedded|edge|server) ;;
  *)
    echo "Unknown TSINK_RESOURCE_PROFILE: $TSINK_RESOURCE_PROFILE (expected: test|embedded|edge|server)" >&2
    exit 1
    ;;
esac

export TSINK_OOO_MAX_SECONDS="${TSINK_OOO_MAX_SECONDS:-300}"
export TSINK_OOO_PERMILLE="${TSINK_OOO_PERMILLE:-250}"
export TSINK_OOO_CROSS_PARTITION_PERMILLE="${TSINK_OOO_CROSS_PARTITION_PERMILLE:-0}"
export TSINK_OOO_CROSS_PARTITIONS="${TSINK_OOO_CROSS_PARTITIONS:-0}"
export TSINK_SPARSE_EMIT_PERMILLE="${TSINK_SPARSE_EMIT_PERMILLE:-120}"
export TSINK_SHORT_LIVED_LIFETIME_STEPS="${TSINK_SHORT_LIVED_LIFETIME_STEPS:-512}"
export TSINK_RETENTION_SECONDS="${TSINK_RETENTION_SECONDS:-604800}"
export TSINK_PARTITION_SECONDS="${TSINK_PARTITION_SECONDS:-86400}"
export TSINK_STEP_SECONDS="${TSINK_STEP_SECONDS:-10}"
export TSINK_SETTLE_MILLIS="${TSINK_SETTLE_MILLIS:-1500}"
export TSINK_FAIL_ON_TARGET="${TSINK_FAIL_ON_TARGET:-0}"
export TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES="${TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES:-8}"

prime_points=0
case "$TSINK_PRIME_ALL_SERIES" in
  1|true|TRUE|yes|YES|y|Y) prime_points="$TSINK_ACTIVE_SERIES" ;;
esac

target_total_points=$((TSINK_ACTIVE_SERIES * TSINK_MIN_POINTS_PER_SERIES))
required_ingest_points=$((target_total_points - prime_points))
if (( required_ingest_points < 0 )); then
  required_ingest_points=0
fi

configured_ingest_points=$((TSINK_WARMUP_POINTS + TSINK_MEASURE_POINTS))
if (( configured_ingest_points < required_ingest_points )); then
  TSINK_WARMUP_POINTS=$((required_ingest_points * 3 / 10))
  TSINK_MEASURE_POINTS=$((required_ingest_points - TSINK_WARMUP_POINTS))
fi

cat <<CONFIG
Running workload benchmark with preset=$WORKLOAD_PRESET
  TSINK_RESOURCE_PROFILE=$TSINK_RESOURCE_PROFILE
  TSINK_MEMORY_LIMIT_BYTES=${TSINK_MEMORY_LIMIT_BYTES:-profile-default}
  TSINK_MAINTENANCE_MAX_BYTES_PER_PASS=${TSINK_MAINTENANCE_MAX_BYTES_PER_PASS:-profile-default}
  TSINK_BPP_RUNS=$TSINK_BPP_RUNS
  TSINK_ACTIVE_SERIES=$TSINK_ACTIVE_SERIES
  TSINK_PRIME_ALL_SERIES=$TSINK_PRIME_ALL_SERIES
  TSINK_MIN_POINTS_PER_SERIES=$TSINK_MIN_POINTS_PER_SERIES
  TSINK_WARMUP_POINTS=$TSINK_WARMUP_POINTS
  TSINK_MEASURE_POINTS=$TSINK_MEASURE_POINTS
  TSINK_BATCH_SIZE=$TSINK_BATCH_SIZE
  TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES=$TSINK_MAX_ACTIVE_PARTITION_HEADS_PER_SERIES
  TSINK_OOO_MAX_SECONDS=$TSINK_OOO_MAX_SECONDS
  TSINK_OOO_CROSS_PARTITION_PERMILLE=$TSINK_OOO_CROSS_PARTITION_PERMILLE
  TSINK_OOO_CROSS_PARTITIONS=$TSINK_OOO_CROSS_PARTITIONS
  TSINK_SHORT_LIVED_LIFETIME_STEPS=$TSINK_SHORT_LIVED_LIFETIME_STEPS
  TSINK_RETENTION_SECONDS=$TSINK_RETENTION_SECONDS
  TSINK_PARTITION_SECONDS=$TSINK_PARTITION_SECONDS
CONFIG

case "${TSINK_QUERY_SATURATION_BENCH:-0}" in
  1|true|TRUE|yes|YES|y|Y)
    cat <<QUERY_CONFIG
  TSINK_QUERY_SATURATION_WORKERS=${TSINK_QUERY_SATURATION_WORKERS:-0} (0 uses the profile limit)
  TSINK_QUERY_SATURATION_SERIES=${TSINK_QUERY_SATURATION_SERIES:-4096}
  TSINK_QUERY_SATURATION_POINTS_PER_SERIES=${TSINK_QUERY_SATURATION_POINTS_PER_SERIES:-64}
  TSINK_QUERY_SATURATION_SERIES_PER_QUERY=${TSINK_QUERY_SATURATION_SERIES_PER_QUERY:-128}
  TSINK_QUERY_SATURATION_WRITER_POINTS=${TSINK_QUERY_SATURATION_WRITER_POINTS:-100000}
  TSINK_QUERY_SATURATION_BATCH_SIZE=${TSINK_QUERY_SATURATION_BATCH_SIZE:-4096}
QUERY_CONFIG
    ;;
esac

case "${TSINK_BPP_DRY_RUN:-0}" in
  1|true|TRUE|yes|YES|y|Y) exit 0 ;;
esac

cargo bench --bench workload -- --nocapture
